In [1]:
import pandas as pd
import numpy as np

In [2]:
blend_9413 = pd.read_csv('submission_70_best.csv', index_col='id')
blend_9396 = pd.read_csv('submission_45_best.csv', index_col='id')
blend_9364 = pd.read_csv('submission_80_best.csv', index_col='id')
pasha = pd.read_csv('submission_utirok3.csv', index_col='id')

In [3]:
blend = blend_9364 * 0.25 + blend_9396 * 0.25 + blend_9413 * 0.5
blend

                    x             y            z        Vx        Vy        Vz
id
3927    -24791.379143 -10910.990714  6570.596643  2.614026 -1.303854  1.087100
3928    -21087.663184 -12384.821790  7840.120289  3.219276 -0.994484  0.895765
3929    -16580.244190 -13379.820024  8806.235946  3.877764 -0.539912  0.602018
3930    -11204.152378 -13656.086643  9298.486854  4.582804  0.157743  0.134369
3931     -4935.768784 -12797.196040  9015.645048  5.251184  1.292350 -0.652537
...               ...           ...          ...       ...       ...       ...
1231060  74725.431066 -59961.599680  -409.750375 -0.808648 -1.299637  0.160405
1231061  67864.556763 -68798.637923   773.117361 -1.042304 -1.097227  0.159806
1231062  59387.405290 -76058.245497  1939.978422 -1.250922 -0.869945  0.155767
1231063  49473.439457 -81553.435252  3063.361839 -1.434987 -0.615621  0.147922
1231064  38306.590861 -85069.254515  4112.779482 -1.592954 -0.330266  0.135664

[284071 rows x 6 columns]

In [4]:
blend.to_csv('blend_top3_w.csv')